title: Mozentai
tagline: CyberSec Specialists, Hackers @ Work
description: Do you know if your company is safe enough? Mozentai audits and hardens systems. Ten years in the market, specialists with 10+ and 15+ years of experience.
lang: en-US
show_downloads: false
plugins:
  - jekyll-seo-tag
